In [25]:
import requests
import pandas as pd
import io
a = ['AAPL', 'CHWY', 'MRNA']
for i in a:
    df1 = pd.DataFrame()
#     url = "https://query1.finance.yahoo.com/v7/finance/download/"+i+"?period1=1633376542&period2=1664912542&interval=1d&events=history&includeAdjustedClose=true"
    params = {'period1': '1633376542','period2': '1664912171','interval':'1d','events':'history','includeAdjustedClose':'true'}
    url = "https://query1.finance.yahoo.com/v7/finance/download/"+i
    headers = {'user-agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15'}
    resp = requests.get(url, headers = headers, params = params)
    
    df = pd.read_csv(io.StringIO(resp.content.decode('utf-8')))
    
    print (pd.concat([df1, df]))

           Date        Open        High         Low       Close   Adj Close  \
0    2021-10-04  141.759995  142.210007  138.270004  139.139999  138.364655
1    2021-10-05  139.490005  142.240005  139.360001  141.110001  140.323700
2    2021-10-06  139.470001  142.149994  138.369995  142.000000  141.208725
3    2021-10-07  143.059998  144.220001  142.720001  143.289993  142.491531
4    2021-10-08  144.029999  144.179993  142.559998  142.899994  142.103699
..          ...         ...         ...         ...         ...         ...
248  2022-09-28  147.639999  150.639999  144.839996  149.839996  149.839996
249  2022-09-29  146.100006  146.720001  140.679993  142.479996  142.479996
250  2022-09-30  141.279999  143.100006  138.000000  138.199997  138.199997
251  2022-10-03  138.210007  143.070007  137.690002  142.449997  142.449997
252  2022-10-04  145.029999  146.220001  144.259995  146.100006  146.100006

        Volume
0     98322000
1     80861100
2     83221100
3     61732700
4     58773200
..         ...
248  146691400
249  128138200
250  124705400
251  114311700
252   87830100

[253 rows x 7 columns]
           Date       Open       High        Low      Close  Adj Close  \
0    2021-10-04  67.129997  67.260002  63.419998  64.230003  64.230003
1    2021-10-05  64.389999  65.269997  63.630001  63.959999  63.959999
2    2021-10-06  63.470001  65.514000  63.470001  64.540001  64.540001
3    2021-10-07  65.000000  66.514999  64.650002  64.790001  64.790001
4    2021-10-08  64.790001  65.010002  62.070000  62.599998  62.599998
..          ...        ...        ...        ...        ...        ...
248  2022-09-28  32.980000  33.380001  32.330002  33.090000  33.090000
249  2022-09-29  32.259998  32.584999  30.940001  31.080000  31.080000
250  2022-09-30  30.969999  32.030998  30.360001  30.719999  30.719999
251  2022-10-03  30.770000  31.830000  29.540001  31.219999  31.219999
252  2022-10-04  32.189999  33.160000  32.040001  33.119999  33.119999

      Volume
0    4220300
1    2559600
2    2272000
3    2814300
4    4843600
..       ...
248  2946500
249  2629300
250  2624100
251  2630800
252  2469900

[253 rows x 7 columns]
           Date        Open        High         Low       Close   Adj Close  \
0    2021-10-04  308.880005  330.554993  305.000000  325.839996  325.839996
1    2021-10-05  331.000000  338.032990  327.200012  332.109985  332.109985
2    2021-10-06  318.709991  325.679993  300.619995  302.420013  302.420013
3    2021-10-07  295.459991  317.350006  293.579987  309.359985  309.359985
4    2021-10-08  310.799988  314.049988  297.540009  304.910004  304.910004
..          ...         ...         ...         ...         ...         ...
248  2022-09-28  123.580002  126.290001  121.820000  122.150002  122.150002
249  2022-09-29  119.900002  120.580002  115.029999  118.070000  118.070000
250  2022-09-30  118.440002  122.580002  118.080002  118.250000  118.250000
251  2022-10-03  119.320000  122.398003  115.410004  120.989998  120.989998
252  2022-10-04  123.669998  126.410004  123.500000  125.669998  125.669998

       Volume
0    23331500
1    11637500
2    17457400
3    15791000
4    10631800
..        ...
248   4245900
249   4755200
250   3854200
251   3812200
252   3464300

[253 rows x 7 columns]

In [1]:
import requests
import pandas as pd
import io

company = ['MRNA', 'AAPL', 'PEP']
l = []
dataframe = pd.DataFrame()
for i in company:
    url = "https://query1.finance.yahoo.com/v7/finance/download/"+i
    params = {'period1' : '1633476122', 'period2' : '1665012122', 'interval' : '1d', 'events' : 'history', 'includeAdjustedClose' : 'true'}
    headers = {'user-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}

    resp = requests.get(url, headers = headers, params = params)
    df = pd.read_csv(io.StringIO(resp.content.decode("utf-8")))
    l.append(df)
print(pd.concat([i for i in l],keys = ['APPL', 'MRNA', 'PEP']))

                Date        Open        High         Low       Close  \
APPL 0    2021-10-05  331.000000  338.032990  327.200012  332.109985
     1    2021-10-06  318.709991  325.679993  300.619995  302.420013
     2    2021-10-07  295.459991  317.350006  293.579987  309.359985
     3    2021-10-08  310.799988  314.049988  297.540009  304.910004
     4    2021-10-11  299.320007  314.109985  298.100006  305.100006
...              ...         ...         ...         ...         ...
PEP  248  2022-09-29  168.800003  169.139999  165.000000  166.610001
     249  2022-09-30  167.690002  168.240005  163.009995  163.259995
     250  2022-10-03  163.520004  165.690002  163.020004  165.250000
     251  2022-10-04  167.389999  168.729996  165.550003  167.110001
     252  2022-10-05  166.970001  167.089996  163.729996  166.000000

           Adj Close    Volume
APPL 0    332.109985  11637500
     1    302.420013  17457400
     2    309.359985  15791000
     3    304.910004  10631800
     4    305.100006   7625800
...              ...       ...
PEP  248  166.610001   5167700
     249  163.259995   5970900
     250  165.250000   5093400
     251  167.110001   4596800
     252  166.000000   3538600

[759 rows x 7 columns]